name: Semgrep Differential Scan
on:
  pull_request

jobs:
  semgrep-diff:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      # Step 1: Clone application source code
      - name: clone application source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Configure git
      - name: configure git
        run: |
          git config --global --add safe.directory $(pwd)

      # Step 3: Verify git installation
      - name: verify git installation
        run: git --version

      # Step 4: Differential scan
      - name: differential scan
        run: |
          semgrep scan \
            --error \
            --metrics=off \
            --baseline-commit ${{ github.event.pull_request.base.sha }} \
            --config="p/default"